apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.artifact_id}}
  # You'll usually want to add your resources to the argocd namespace.
  namespace: devopsnow
  # Add a this finalizer ONLY if you want these to cascade delete.
  
spec:
  # The project the application belongs to (our customer bootstrap API create appropriate projects with permissions, but
  # set to default for remote customers as we do not have access to their Argo to bootstrap new projects)
  project: devopsnow

  # Source of the application manifests
  source:
    repoURL: ${{ steps.publish.output.remoteUrl }}.git
    targetRevision: HEAD
    path: manifests

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using "retry" field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy