apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.artifact_id}}-deployment
  labels:
    app: ${{values.artifact_id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.artifact_id}}
  template:
    metadata:
      labels:
        app: ${{values.artifact_id}}
    spec:
      containers:
      - name: ${{values.artifact_id}}
        image: "registry.devopsnow.io/internal/${{values.component_id}}:latest"
        ports:
        - containerPort: 8081
